// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gilvdghybdrntpzlgezo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbHZkZ2h5YmRybnRwemxnZXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3ODQ1NjgsImV4cCI6MjA1MjM2MDU2OH0.lI7yvmVFCghF4-3wkn6k0lG7xiukgwuxJPmYOp0zphA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);